(:module
    (:symbol entry)
    (:arguments
        (:concept X)
        (:role O)
        (:boolean B)
        (:numerical N)
    )
    (:registers
        (:concept r0)
        (:role r0)
    )
    (:entry m0)
    (:memory m0 m1)
    (:features
        (:concept
            (:symbol linked)
            (:expression
                (c_some
                    (r_register r0)
                    (c_top)
                )
            )
        )
    )
    (:rules)
)

