from pytyr.serialization import Dictionaries as Dictionaries
from pyyggdrasil.serialization import JSONValue as JSONValue, Row as Row


def register_table(dictionaries: Dictionaries, native_type: type[object], name: str, prefix: str) -> None: ...
def serialize(dictionaries: Dictionaries, value: object) -> JSONValue: ...
def table(dictionaries: Dictionaries, native_type: type[object]) -> list[Row]: ...
