(:module
    (:symbol entry)
    (:arguments)
    (:registers)
    (:entry m0)
    (:memory m0 m1)
    (:features
        (:concept
            (:symbol B)
            (:expression
                (c_top)
            )
        )
    )
    (:rules
        (:rule
            (:symbol auto7)
            (:expression
                (:source-memory m0)
                (:target-memory m1)
                (:do
                    (:conditions)
                    (:action "pick")
                    (:arguments B Missing B)
                    (:effects)
                )
            )
        )
    )
)

