# Import all classes and functions for better IDE support

from . import semantics

from ...._pyrunir.kr.dl.ext import (
    BooleanArgument,
    BooleanArgumentData,
    BooleanArgumentIdentifier,
    BooleanArgumentIndex,
    BooleanConstructorIndex,
    ConceptArgument,
    ConceptArgumentData,
    ConceptArgumentIdentifier,
    ConceptArgumentIndex,
    ConceptConstructorIndex,
    ConceptRegister,
    ConceptRegisterData,
    ConceptRegisterIdentifier,
    ConceptRegisterIndex,
    ConstructorRepository,
    ConstructorRepositoryFactory,
    NumericalArgument,
    NumericalArgumentData,
    NumericalArgumentIdentifier,
    NumericalArgumentIndex,
    NumericalConstructorIndex,
    RoleArgument,
    RoleArgumentData,
    RoleArgumentIdentifier,
    RoleArgumentIndex,
    RoleConstructorIndex,
    RoleRegister,
    RoleRegisterData,
    RoleRegisterIdentifier,
    RoleRegisterIndex,
)
