set(PYRUNIR_STUB_ROOT "${CMAKE_INSTALL_PREFIX}/pyrunir")

if(EXISTS "${PYRUNIR_STUB_ROOT}")
    file(GLOB_RECURSE PYRUNIR_STUB_FILES "${PYRUNIR_STUB_ROOT}/*.pyi")

    foreach(PYRUNIR_STUB_FILE IN LISTS PYRUNIR_STUB_FILES)
        file(READ "${PYRUNIR_STUB_FILE}" PYRUNIR_STUB_CONTENT)
        set(PYRUNIR_PATCHED_STUB_CONTENT "${PYRUNIR_STUB_CONTENT}")

        string(REPLACE "pyrunir._pyrunir." "pyrunir." PYRUNIR_PATCHED_STUB_CONTENT "${PYRUNIR_PATCHED_STUB_CONTENT}")
        string(REPLACE "pytyr._pytyr." "pytyr." PYRUNIR_PATCHED_STUB_CONTENT "${PYRUNIR_PATCHED_STUB_CONTENT}")
        string(REPLACE "pyrunir._pyrunir" "pyrunir" PYRUNIR_PATCHED_STUB_CONTENT "${PYRUNIR_PATCHED_STUB_CONTENT}")
        string(REPLACE "pytyr._pytyr" "pytyr" PYRUNIR_PATCHED_STUB_CONTENT "${PYRUNIR_PATCHED_STUB_CONTENT}")

        if(NOT PYRUNIR_STUB_CONTENT STREQUAL PYRUNIR_PATCHED_STUB_CONTENT)
            file(WRITE "${PYRUNIR_STUB_FILE}" "${PYRUNIR_PATCHED_STUB_CONTENT}")
        endif()
    endforeach()
endif()
